import clsx from 'clsx'
import './globals.css'
import { Press_Start_2P } from 'next/font/google'

const font = Press_Start_2P({ weight: '400', subsets: ['latin-ext'] })

export const metadata = {
  title: 'Greedy Band',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout ({
  children
}: Props): JSX.Element {
  return (
    <html lang="es">
      <body className={clsx(font.className, 'bg-gray-900 text-white min-h-screen')}>
        {children}
      </body>
    </html>
  )
}
